[package]
name = "rocto"
version = "0.1.0"
authors = ["jdeeny <jdeeny@gmail.com>"]

[dependencies]
nom = { git = "https://github.com/jdeeny/nom.git", version = "1.2.4" }
chip8 = { git = "https://github.com/jdeeny/rust-chip8.git" , version = "0.2.0" }
